controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    go2_controller:
      type: go2_controller/Go2Controller
  
go2_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint

    command_interfaces: 
      - effort
    
    state_interfaces:
      - position
      - velocity
      - effort

    gain:
      Kp: 60.0
      Kd: 5.0
      
    
    # joints_references: [-0.05, 0.05, -1.18, -0.05, 0.05, -1.18, -0.05, -1.5, 1.18, -0.05, -1.5, 1.18]
    joints_references: [ 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, -0.2, 1.36, -2.65, 0.2, 1.36, -2.65]
    
    robot_states_feedabck_rate: 100.0 #Hz