# gz topic published by the simulator core
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Odometry from Gazebo to ROS2
- ros_topic_name: "odom_gz"
  gz_topic_name: "/model/go2/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS



  # # Joint states from Gazebo to ROS2
  # - ros_topic_name: "/joint_states_gz"
  #   gz_topic_name: "/world/default/model/go2/joint_state"
  #   ros_type_name: "sensor_msgs/msg/JointState"
  #   gz_type_name: "gz.msgs.Model"
  #   direction: GZ_TO_ROS