<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>utils</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="mobilab@todo.todo">mobilab</maintainer>
  <license>TODO: License declaration</license>

<!-- Dependencies required at build and runtime -->
  <depend>ament_cmake</depend>

  <!-- Buildtool dependency -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Export the package -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
